/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AppMainFrame.java
 *
 * Created on Nov 5, 2010, 11:10:31 AM
 */

package org.ioe.bct.p2pconference.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

import org.ioe.bct.p2pconference.dataobject.ContactList;
import org.ioe.bct.p2pconference.prototype.pattern.observer.Subject;

/**
 *
 * @author kusu
 */
public class AppMainFrame extends javax.swing.JFrame {
   
    /** Creates new form AppMainFrame */
    public AppMainFrame() {
        super("P2P Video Conferencing...");
        initComponents();
    }

    public void disposeLoginBox() {
        loginBox.dispose();
    }

    public void createMenus() {
        menubar=new JMenuBar();
        JMenu contactMenu=new JMenu("Contacts");
        JMenuItem addContactMenu=new JMenuItem("Add Contact");
        JMenuItem createGroupMenu=new JMenuItem("Create Group");

        addContactMenu.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                addContact();
            }
        });
        

        contactMenu.add(addContactMenu);
        contactMenu.add(createGroupMenu);

        setJMenuBar(menubar);
        menubar.add(contactMenu);
        menuHash.put("contacts",contactMenu);
        
    }

    public void addContact() {
       
        SearchContactDialog searchContact=new SearchContactDialog(this, true);
       searchContact.setVisible(true);

    }

    public void hideLoginBox() {
        loginBox.setVisible(false);
    }

    public void loadLoginBox() {
        if(loginBox==null) {
            loginBox=new LoginDialog(this, "Login..").init();

        }
        loginBox.setVisible(true);
    }

    public AppMainFrame load(String userName,String pass) {
        this.username=userName;
        this.password=pass;
        createMenus();
        setBounds(150, 100, 800, 600);
        return this;
    }

    public void loadContactList() {
         
        contListPanel=new ContactListPanel(contactList);
        contGroupPanel=new GroupsPanel();
       contactListTab=new JTabbedPane(JTabbedPane.TOP);
        contactListTab.addTab("Contacts", contListPanel);
        contactListTab.addTab("Groups", contGroupPanel);
        
        contactPanel.add(contactListTab,BorderLayout.CENTER);
        jSplitPane1.setDividerLocation(200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        contactPanel = new JPanel(new BorderLayout());
        ;
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contactPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        loadContactList();
        jSplitPane1.setLeftComponent(contactPanel);

        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Send Message");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        for(int i=0;i<9;i++) {
            JPanel p=new JPanel();
            p.setBackground(Color.black);
            jPanel2.add(p);

        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
   
    public Subject getContactList() {
        return contactList;
    }

   
    private String username;
    private String password;
    private static LoginDialog loginBox;
    private JMenuBar menubar;
    private HashMap menuHash=new HashMap();
    
    private Subject contactList=new ContactList();
    private ContactListPanel contListPanel;
    private GroupsPanel contGroupPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contactPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private JTabbedPane contactListTab;
}
