/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CallResponsePanel.java
 *
 * Created on Jan 8, 2011, 9:09:38 PM
 */

package org.ioe.bct.p2pconference.ui;

import org.ioe.bct.p2pconference.patterns.mediator.Mediator;
import org.ioe.bct.p2pconference.ui.controls.ConferenceMediator;

/**
 *
 * @author kusu
 */
public class CallResponsePanel extends javax.swing.JPanel implements Runnable {

    private Mediator confMediator;
    private String sender;

    /** Creates new form CallResponsePanel */
    public CallResponsePanel(String send,Mediator m) {
        this.confMediator=m;
        this.sender=send;
        initComponents();
        callLabel.setText(sender);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptCallButton = new javax.swing.JButton();
        declineCallButton = new javax.swing.JButton();
        callerLabel = new javax.swing.JLabel();
        callLabel = new javax.swing.JLabel();

        acceptCallButton.setText("Accept Call");
        acceptCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptCallButtonActionPerformed(evt);
            }
        });

        declineCallButton.setText("Decline");
        declineCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineCallButtonActionPerformed(evt);
            }
        });

        callerLabel.setText(" ");

        callLabel.setText("Calling...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(callerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(callLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptCallButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(declineCallButton)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callLabel)
                    .addComponent(callerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptCallButton)
                    .addComponent(declineCallButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptCallButtonActionPerformed
        // TODO add your handling code here:
        confMediator.sendMessage(ConferenceMediator.PRIVATE_CALL_ACCEPT_MSGQ, null, ConferenceMediator.PRIVATE_CALL_ACCEPT_CODE+"\n"+sender);
    }//GEN-LAST:event_acceptCallButtonActionPerformed

    private void declineCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineCallButtonActionPerformed
        // TODO add your handling code here:
        confMediator.sendMessage(ConferenceMediator.PRIVATE_CALL_REJECT_MSGQ, null, ConferenceMediator.PRIVATE_CALL_REJECT_CODE+"\n"+sender);
    }//GEN-LAST:event_declineCallButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptCallButton;
    private javax.swing.JLabel callLabel;
    private javax.swing.JLabel callerLabel;
    private javax.swing.JButton declineCallButton;
    // End of variables declaration//GEN-END:variables

    public void appendDots(int n) {
        String appString="";
        for(int i=0;i<n;i++) {
            appString+=".";
        }
        callLabel.setText("Calling"+appString);
    }

    public void run() {
        int count=1;
        while (true) {
            appendDots(count);
            count++;
            if(count>3){
                count=0;
            }
            pause(1000);
        }
    }
   public void pause(long time) {
        try {
            Thread.sleep(time);
        }
        catch (InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

}
