/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CallResponsePanel.java
 *
 * Created on Jan 8, 2011, 9:09:38 PM
 */

package org.ioe.bct.p2pconference.ui;

import org.ioe.bct.p2pconference.patterns.mediator.Mediator;
import org.ioe.bct.p2pconference.ui.controls.ConferenceMediator;

/**
 *
 * @author kusu
 */
public class CallResponsePanel extends javax.swing.JPanel {

    private Mediator confMediator;

    /** Creates new form CallResponsePanel */
    public CallResponsePanel(Mediator m) {
        this.confMediator=m;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptCallButton = new javax.swing.JButton();
        declineCallButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        acceptCallButton.setText("Accept Call");
        acceptCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptCallButtonActionPerformed(evt);
            }
        });

        declineCallButton.setText("Decline");
        declineCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineCallButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(" ");

        jLabel2.setText("Calling...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptCallButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(declineCallButton)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptCallButton)
                    .addComponent(declineCallButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptCallButtonActionPerformed
        // TODO add your handling code here:
        confMediator.sendMessage(ConferenceMediator.PRIVATE_CALL_ACCPTED, null, "Call Accepted");
    }//GEN-LAST:event_acceptCallButtonActionPerformed

    private void declineCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineCallButtonActionPerformed
        // TODO add your handling code here:
        confMediator.sendMessage(ConferenceMediator.PRIVATE_CALL_REJECTED, null, "Call Accepted");
    }//GEN-LAST:event_declineCallButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptCallButton;
    private javax.swing.JButton declineCallButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
