/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GroupsPanel.java
 *
 * Created on Nov 5, 2010, 12:29:08 PM
 */

package org.ioe.bct.p2pconference.ui;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import org.ioe.bct.p2pconference.core.PeerGroupOrganizer;
import org.ioe.bct.p2pconference.dataobject.ProtectedPeerGroup;
import org.ioe.bct.p2pconference.prototype.patterns.mediator.Colleague;
import org.ioe.bct.p2pconference.prototype.patterns.mediator.Mediator;
import org.ioe.bct.p2pconference.ui.controls.ConferenceMediator;

/**
 *
 * @author kusu
 */
public class GroupsPanel extends javax.swing.JPanel implements Colleague{

    

    private ArrayList<ProtectedPeerGroup> peerGroupsList=new ArrayList<ProtectedPeerGroup>();
    private Mediator confMediator;
    /** Creates new form GroupsPanel */

      public GroupsPanel(Mediator m) {
        initComponents();
        confMediator=m;
       
    }

    private void initList() {
        groupsListUI.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        groupsListUI.setCellRenderer(new ListCellRenderer() {

            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

                if(value instanceof JPanel) {
                    Component component=(Component) value;
                     component.setForeground (Color.white);
                     component.setBackground (isSelected ? Color.MAGENTA : Color.white);
                    return component;
                }
             else {
                     return new JLabel("");
             }
            }
        });

        groupsListUI.setListData(peerGroupsList.toArray());
    }

  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupsListUI = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        groupsListUI.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupsListUI.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupsListUIValueChanged(evt);
            }
        });
        initList();
        jScrollPane1.setViewportView(groupsListUI);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void groupsListUIValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupsListUIValueChanged
        // TODO add your handling code here:
        Object dataItem=groupsListUI.getSelectedValue();
        confMediator.sendMessage(ConferenceMediator.CONT_SELECTION_CHANGED, this, dataItem);

    }//GEN-LAST:event_groupsListUIValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupsListUI;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void receive(String message, Colleague sender, Object body) {
//        throw new UnsupportedOperationException("Not supported yet.");
        JDialog senderc=(JDialog)sender;
        senderc.dispose();
        if(message.equalsIgnoreCase(ConferenceMediator.GROUP_ADDED)) {
            PeerGroupOrganizer orgn=(PeerGroupOrganizer)body;
            peerGroupsList=orgn.getAllPeerGroups();
            System.out.println(peerGroupsList.size());
            updateGroupList();
        }
    }

    private void updateGroupList() {
        Iterator it=peerGroupsList.iterator();
        while (it.hasNext()) {
        ProtectedPeerGroup current=peerGroupsList.iterator().next();
        String groupName=current.getGroupName();
            JLabel label=new JLabel(groupName);
            JPanel panel=new JPanel();
            panel.add(label);
            groupsListUI.add(panel);
           System.out.println(groupName);
        }
         groupsListUI.validate();
    }

    public void setMediator(Mediator m) {
//        throw new UnsupportedOperationException("Not supported yet.");
         m.addColleague(this);
    }
 
}
