/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JoinGroupDialog.java
 *
 * Created on Dec 31, 2010, 12:32:29 PM
 */

package org.ioe.bct.p2pconference.ui;
import javax.swing.JOptionPane;
import org.ioe.bct.p2pconference.core.PeerGroupService;
import org.ioe.bct.p2pconference.dataobject.ProtectedPeerGroup;
import org.ioe.bct.p2pconference.prototype.patterns.mediator.Colleague;
import org.ioe.bct.p2pconference.prototype.patterns.mediator.Mediator;
import org.ioe.bct.p2pconference.ui.controls.ConferenceMediator;
/**
 *
 * @author Administrator
 */
public class JoinGroupDialog extends javax.swing.JDialog implements Colleague{

    private final String EMPTY_FIELDS="Please fill in all the values.";
    private final String WRONG_AUTHENTICATION="Incorrect Password!";
    private PeerGroupService peerGroupService;
    /** Creates new form JoinGroupDialog */
    public JoinGroupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        peerGroupService=new PeerGroupService();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        authenticationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Authentication");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(94, 161, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Requesting to join the group. Please enter the following details......");

        authenticationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Authentication Required"));
        authenticationPanel.setName(""); // NOI18N

        jLabel2.setText("Login :");

        jLabel3.setText("Password:");

        jButton1.setText("Join Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout authenticationPanelLayout = new javax.swing.GroupLayout(authenticationPanel);
        authenticationPanel.setLayout(authenticationPanelLayout);
        authenticationPanelLayout.setHorizontalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenticationPanelLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );
        authenticationPanelLayout.setVerticalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authenticationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authenticationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String message="";
        if(loginTextField.getText().isEmpty() || passwordTextField.getPassword().length==0)
        {
            message=EMPTY_FIELDS;
        }
//        else if(!(loginTextField.getText().equals(login) && passwordTextField.getText().equals(password)))
//        {
//            message=WRONG_AUTHENTICATION;
//        }
        else
        {
            if(pPeerGroup.getPeerGroup()==null)
                JOptionPane.showMessageDialog(this, "Null value of peerGroup");
            peerGroupService.joinPeerGroup(pPeerGroup.getPeerGroup(), loginTextField.getText(), passwordTextField.getText());
        }
        errorMessageLabel.setText(message);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JoinGroupDialog dialog = new JoinGroupDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticationPanel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField passwordTextField;
    // End of variables declaration//GEN-END:variables
    //Variables declartion - Modifiable
    private ProtectedPeerGroup pPeerGroup;
    private Mediator confMediator;
    private String login;
    private String password;
    //End of variable declaration
    public void receive(String message, Colleague sender, Object body) {
       // throw new UnsupportedOperationException("Not supported yet.");
        if(message.equals(ConferenceMediator.JOIN_GROUP)){
            this.setVisible(true);
            pPeerGroup=(ProtectedPeerGroup)body;
            setAuthenticationParameter(pPeerGroup);

        }
    }
    private void setAuthenticationParameter(ProtectedPeerGroup pPGRP)
    {
        login=pPGRP.getGroupLoginName();
        password=pPGRP.getPassword();
        JOptionPane.showMessageDialog(this, login +" & "+password);

    }
    public void setMediator(Mediator m) {
        m.addColleague(this);
        confMediator=m;
       // throw new UnsupportedOperationException("Not supported yet.");
    }

}
