/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchContactDialog.java
 *
 * Created on Nov 5, 2010, 1:49:26 PM
 */

package org.ioe.bct.p2pconference.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import org.ioe.bct.p2pconference.core.ContactRequestManager;
import org.ioe.bct.p2pconference.core.db.DBHandler;
import org.ioe.bct.p2pconference.ui.controls.ContactList;
import org.ioe.bct.p2pconference.dataobject.Request;
import org.ioe.bct.p2pconference.dataobject.User;

/**
 *
 * @author kusu
 */
public class SearchContactDialog extends javax.swing.JDialog {

    /** Creates new form SearchContactDialog */
    public SearchContactDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Add Contact");
        setBounds(parent.getX()+100,parent.getY()+50,40,30);
        initComponents();
        
        listData=new ArrayList<User>();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();
        addButtton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add a contact");

        jLabel2.setText("Enter name or email:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Results"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(resultList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        addButtton.setText("Add");
        addButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButtton, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(addButtton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButttonActionPerformed
        // TODO add your handling code here:
        String selectedContact=resultList.getSelectedValue().toString();
        Request req=new Request(selectedContact, "Hello!");


        if(selectedContact==null) {
            JOptionPane.showMessageDialog(null, "No contact Selected.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         else {
            AppMainFrame parent=(AppMainFrame)this.getParent();
            
            ContactList ctList=(ContactList) parent.getContactList();
            ContactRequestManager addreq=new ContactRequestManager(ctList);
            ctList.addContact(req);
            this.dispose();
        }
        
    }//GEN-LAST:event_addButttonActionPerformed

   

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try {
            if(searchField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter search criteria.","Missing Field",JOptionPane.ERROR_MESSAGE);
                return;
            }
            dbHandler.initConnection();

           listData=dbHandler.searchContact(searchField.getText());
           Iterator<User> it=listData.iterator();
           ArrayList uiList=new ArrayList();
           while(it.hasNext()) {
              uiList.add(it.next().getName());
           }
           resultList.setListData(uiList.toArray());
        }
       
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
         catch (Exception cnf) {
            JOptionPane.showMessageDialog(null, cnf.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
    * @param args the command line arguments
    */

    
    private DBHandler dbHandler=new DBHandler();
     private ArrayList<User> listData;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList resultList;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

}
